version: "3.8"

services:
  app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    environment:
      SPRING_DATA_MONGODB_DATABASE: ${SPRING_DATA_MONGODB_DATABASE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}

volumes:
  maven_cache:
