name: Docker Build and Push

on:
  workflow_run:
    workflows:
      - "Java CI"
    types:
        - completed
    branches:
        - main
jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      statuses: write

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN}}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/gym-db:latest
            build-args: |
              SPRING_DATA_MONGODB_DATABASE=${{ secrets.SPRING_DATA_MONGODB_DATABASE }}
              SPRING_DATA_MONGODB_URI=${{ secrets.SPRING_DATA_MONGODB_URI }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

