name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: List files in the repository
          run: ls -la

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN}}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/gym-db:latest
            build-args: |
              SPRING_DATA_MONGODB_DATABASE=${{ secrets.SPRING_DATA_MONGODB_DATABASE }}
              SPRING_DATA_MONGODB_URI=${{ secrets.SPRING_DATA_MONGODB_URI }}

